exclude_keywords:
  - "货币"
  - "添益"
  - "日利"
  - "债"
  - "国债"
  - "可转债"
  - "短融"
  - "现金"
  - "沪深300"
  - "中证500"
  - "中证1000"
  - "中证2000"
  - "中证A500"
  - "A500"
  - "上证50"
  - "上证指数"
  - "上证180"
  - "深证100"
  - "深成"
  - "创业板"
  - "创业大盘"
  - "科创50"
  - "科创100"
  - "科创综指"
  - "科创200"
  - "双创"
  - "科创创业"
  - "国证"
  - "中证A50"
  - "中证800"
  - "A50ETF"
  - "MSCI"
  - "红利"
  - "低波"
  - "成长"
  - "价值"
  - "高股息"
  - "财富宝"
  - "科技ETF"
  - "科技龙头"
  - "央企科技"
  - "张江"
  - "TMT"
  - "恒生"
  - "港股"
  - "中概"
  - "纳指"
  - "纳斯达克"
  - "标普"
  - "日经"
  - "道琼斯"
  - "亚太"
  - "香港"
  - "美国"
  - "德国"
  - "法国"
  - "日本"
  - "东证"
  - "黄金"
  - "金ETF"
  - "豆粕"
  - "油气"

industry_keywords:
  电子:
    - "芯片"
    - "半导体"
    - "电子"
    - "集成电路"
    - "消电"
  通信:
    - "通信"
    - "5G"
    - "云计算"
    - "卫星"
  计算机:
    - "计算机"
    - "软件"
    - "信创"
    - "人工智能"
    - "AI"
    - "机器人"
    - "游戏"
    - "大数据"
    - "数字经济"
    - "信息技术"
    - "科创信息"
  机械设备:
    - "机械"
    - "工业母机"
    - "机床"
    - "工程机械"
  汽车:
    - "汽车"
    - "新能源车"
    - "智能车"
    - "智能驾驶"
    - "电池"
  医药生物:
    - "医药"
    - "医疗"
    - "创新药"
    - "生物"
    - "疫苗"
    - "中药"
  银行:
    - "银行"
  非银金融:
    - "证券"
    - "券商"
    - "保险"
    - "金融"
    - "非银"
  电力设备:
    - "光伏"
    - "新能源"
    - "电力设备"
    - "储能"
    - "电网"
    - "风电"
  有色金属:
    - "有色"
    - "稀土"
    - "金属"
    - "贵金属"
  国防军工:
    - "军工"
    - "国防"
    - "航空"
    - "航天"
    - "船舶"
  基础化工:
    - "化工"
    - "化学"
    - "材料"
    - "塑料"
  煤炭:
    - "煤炭"
  石油石化:
    - "能源"
    - "石油"
    - "油气"
  食品饮料:
    - "食品"
    - "饮料"
    - "酒"
    - "白酒"
  农林牧渔:
    - "农业"
    - "养殖"
    - "畜牧"
  家用电器:
    - "家电"
  房地产:
    - "房地产"
    - "物业"
  建筑材料:
    - "建材"
    - "水泥"
    - "玻璃"
  建筑装饰:
    - "建筑"
    - "基建"
  交通运输:
    - "物流"
    - "运输"
    - "航运"
    - "航空"
  公用事业:
    - "电力"
    - "燃气"
    - "环保"
    - "绿电"
  钢铁:
    - "钢铁"
  传媒:
    - "传媒"
    - "影视"
    - "出版"
    - "动漫"
  商贸零售:
    - "消费"
    - "零售"
    - "电商"
  社会服务:
    - "旅游"
    - "教育"
    - "酒店"
  环保:
    - "环保"
    - "环境"
  美容护理:
    - "美容"
    - "化妆"
